### ISSUE TITLE
Giving NaN to React Spring

### ISSUE THREAD

**Issue by tjomson** [git-truck/git-truck#317]
Changing to tree map causes this:
![billede](https://user-images.githubusercontent.com/23435481/157858624-e66266c2-d5a0-4f3e-b04a-2e34d2cffe9e.png)
![billede](https://user-images.githubusercontent.com/23435481/157858669-ca101e58-509f-43bd-9e8e-21d620f923d0.png)
![billede](https://user-images.githubusercontent.com/23435481/157858720-32300ca2-e4ec-4938-957a-27cfed1d0e32.png)

**Comment by joglr** [comment]
I have narrowed down the issue to being that we only generate the new d3 data after we have already changed the chart type.

This means, that when switching chart type this happens:
```
s0
chartType: BubbleChart
nodes: CircleNodes

** user changes chart type **

s1
chartType: TreeMap
nodes: CircleNodes

s2
chartType: TreeMap
nodes: RectangleNodes
```

This works fine for the initial render, because we don't change chart type from first render, to when we generate the nodes with d3.
