### ISSUE TITLE
equal size does not work in treemap layout? 

### ISSUE THREAD

**Issue by mircealungu** [git-truck/git-truck#715]
works for bubble chart
<img width="1504" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/4f6da046-9d91-4ca9-a184-ff6ac9308b23">

but not for treemap
<img width="1503" alt="image" src="https://github.com/git-truck/git-truck/assets/464519/3a20c9c6-bbd5-4885-985b-88ef69f6a0c7">

**Comment by joglr** [comment]
Did you expect the rectangles to have similar dimensions or similar area?

**Comment by mircealungu** [comment]
I did expect that. Or at least very close areas. Which is not the case at the moment. 
That being said, I'm not convinced of the importance of Equal in general. So if it's not an easy fix, then probably it's fine to go with "won't fix".

**Comment by joglr** [comment]
> I did expect that. Or at least very close areas. Which is not the case at the moment. 
> That being said, I'm not convinced of the importance of Equal in general. So if it's not an easy fix, then probably it's fine to go with "won't fix".

For them to be more equal, the algorithm should allow empty space, for example, if you look at the yellow files, where there is an odd number, it fills out the rest for the last file.

I don't know if there is a way to configure this behavior. My guess is it would also bias other sizes metrics, but it is not as noticeable, since you are not expecting a specific size of the rectangle.

Actions:
 - Figure out if D3 treemap algorithm has an option for allowing empty space, to increase accuracy of metric representation.

**Comment by joglr** [comment]
Might be able to improve it by changing the mode:

https://d3-wiki.readthedocs.io/zh-cn/master/Treemap-Layout/#mode

**Comment by joglr** [comment]
This was fixed by @tjomson in #731 i believe.
